### ISSUE TITLE
Thorvald Tasks [to move to Thorvald repo]

### ISSUE THREAD

**Issue by Jailander** [LCAS/Rusty#13]
Tasks to do in Thorvald:

- [ ] Remind @gcielniak to include @larsgrim @vigneshrajaponnambalam to the Thorvald team so they have access to the repo, also include Glenn

- [ ] Once that is done move this issue to that repo.

- [ ] Finish simulation ( @jailander ), also evaluate V-rep

- [ ] Send Inertias for the robot links from 3D model, needed for previous task ( @larsgrim ) or 3D mesh

- [ ] set up nav stack ( @jailander )

- [ ] Check https://github.com/strands-project/strands_apps/tree/indigo-devel/ramp_climb and https://github.com/strands-project/strands_apps/tree/indigo-devel/door_pass for deveolping strawberry tunnel navigation action @vigneshrajaponnambalam

- [ ] Write tutorials properly!!! ( @jailander ) use @Overland55 as guinea pig

- [ ] We need to discuss sensor rack (PC?, IMU, GPS, mounting, Velodyne, can we use it on Rusty? (the husky robot))

- [ ] Clean repo and give better names to packages

- [ ] Discuss ROS version

- [ ] Make PR with latest changes on Thorvald @larsgrim

- [ ] Tutorial for bag usage ( @Overland55 ), Test NDT with this ( @azaganidis )

**Comment by gcielniak** [comment]
@Jailander I think I did add the guys. See my comments in the Thorvald repo. You should also have rights to add people to that team.

**Comment by Jailander** [comment]
Closing as the issue is now on the Thorvald repository
